// role_service.dart
import 'package:hotel_management_system/data/models/role_model.dart';
import 'package:hotel_management_system/data/models/permission_model.dart';
import 'package:hotel_management_system/data/repositories/role_repository.dart';

class RoleService {
  final RoleRepository _repository;

  RoleService(this._repository);

  // ---------- CRUD OPERATIONS ----------

  Future<List<RoleModel>> getRolesByBusiness(String businessId) async {
    try {
      if (businessId.isEmpty) {
        throw Exception('Business ID cannot be empty');
      }
      return await _repository.getRolesByBusiness(businessId);
    } catch (e) {
      throw Exception('Failed to fetch roles: $e');
    }
  }

  Future<RoleModel?> getRoleById(String roleId) async {
    try {
      if (roleId.isEmpty) {
        throw Exception('Role ID cannot be empty');
      }
      return await _repository.getRoleById(roleId);
    } catch (e) {
      throw Exception('Failed to fetch role: $e');
    }
  }

  Future<void> createRole(RoleModel role) async {
    try {
      // -----------ROLE ID WILL BE AUTO GENERATED BY FIRESTORE-----------
      // Validate role data
      // if (!isValidRoleId(role.id)) {
      //   throw Exception(
      //     'Invalid role ID format. Use lowercase letters, numbers, underscores, and hyphens only.',
      //   );
      // }

      if (!isValidRoleName(role.name)) {
        throw Exception('Role name must be between 1-100 characters');
      }

      if (role.businessId.isEmpty) {
        throw Exception('Business ID cannot be empty');
      }

      if (role.permissions.isEmpty) {
        throw Exception('Role must have at least one permission');
      }

      // Check if role already exists
      final exists = await _repository.roleExists(role.id);

      if (exists) {
        throw Exception(
          'Role with ID "${role.id}" already exists in this business',
        );
      }

      await _repository.createRole(role);
    } catch (e) {
      if (e is Exception) rethrow;
      throw Exception('Failed to create role: $e');
    }
  }

  Future<void> updateRole(RoleModel role) async {
    try {
      // Validate role exists
      final existingRole = await _repository.getRoleById(role.id);
      if (existingRole == null) {
        throw Exception('Role with ID "${role.id}" not found in this business');
      }

      // Validate updated data
      if (!isValidRoleName(role.name)) {
        throw Exception('Role name must be between 1-100 characters');
      }

      if (role.permissions.isEmpty) {
        throw Exception('Role must have at least one permission');
      }

      await _repository.updateRole(role);
    } catch (e) {
      if (e is Exception) rethrow;
      throw Exception('Failed to update role: $e');
    }
  }

  Future<void> deleteRole(String roleId, String businessId) async {
    try {
      if (roleId.isEmpty) {
        throw Exception('Role ID cannot be empty');
      }
      if (businessId.isEmpty) {
        throw Exception('Business ID cannot be empty');
      }

      // Check if role exists
      final exists = await _repository.roleExists(roleId);
      if (!exists) {
        throw Exception('Role with ID "$roleId" not found in this business');
      }

      await _repository.deleteRole(roleId);
    } catch (e) {
      if (e is Exception) rethrow;
      throw Exception('Failed to delete role: $e');
    }
  }

  // ---------- PERMISSION MANAGEMENT ----------

  Future<void> addPermissionToRole(
    String roleId,
    String businessId,
    PermissionModel permission,
  ) async {
    try {
      if (roleId.isEmpty || businessId.isEmpty) {
        throw Exception('Role ID and Business ID cannot be empty');
      }

      final role = await _repository.getRoleById(roleId);
      if (role == null) {
        throw Exception('Role with ID "$roleId" not found');
      }

      // Check if permission already exists in role
      if (role.permissions.any((p) => p.id == permission.id)) {
        throw Exception('Permission already exists in this role');
      }

      final updatedPermissions = List<PermissionModel>.from(role.permissions)
        ..add(permission);
      final updatedRole = role.copyWith(permissions: updatedPermissions);

      await _repository.updateRole(updatedRole);
    } catch (e) {
      if (e is Exception) rethrow;
      throw Exception('Failed to add permission to role: $e');
    }
  }

  Future<void> removePermissionFromRole(
    String roleId,
    String businessId,
    String permissionId,
  ) async {
    try {
      if (roleId.isEmpty || businessId.isEmpty || permissionId.isEmpty) {
        throw Exception(
          'Role ID, Business ID, and Permission ID cannot be empty',
        );
      }

      final role = await _repository.getRoleById(roleId);
      if (role == null) {
        throw Exception('Role with ID "$roleId" not found');
      }

      // Check if permission exists in role
      if (!role.permissions.any((p) => p.id == permissionId)) {
        throw Exception('Permission not found in this role');
      }

      final updatedPermissions = role.permissions
          .where((p) => p.id != permissionId)
          .toList();

      // Ensure role has at least one permission
      if (updatedPermissions.isEmpty) {
        throw Exception('Role must have at least one permission');
      }

      final updatedRole = role.copyWith(permissions: updatedPermissions);
      await _repository.updateRole(updatedRole);
    } catch (e) {
      if (e is Exception) rethrow;
      throw Exception('Failed to remove permission from role: $e');
    }
  }

  Future<void> updateRolePermissions(
    String roleId,
    String businessId,
    List<PermissionModel> permissions,
  ) async {
    try {
      if (roleId.isEmpty || businessId.isEmpty) {
        throw Exception('Role ID and Business ID cannot be empty');
      }

      if (permissions.isEmpty) {
        throw Exception('Role must have at least one permission');
      }

      final role = await _repository.getRoleById(roleId);
      if (role == null) {
        throw Exception('Role with ID "$roleId" not found');
      }

      final updatedRole = role.copyWith(permissions: permissions);
      await _repository.updateRole(updatedRole);
    } catch (e) {
      if (e is Exception) rethrow;
      throw Exception('Failed to update role permissions: $e');
    }
  }

  // ---------- QUERY OPERATIONS ----------

  Future<List<RoleModel>> searchRoles(
    String businessId,
    String searchTerm, {
    int limit = 20,
  }) async {
    try {
      if (businessId.isEmpty) {
        throw Exception('Business ID cannot be empty');
      }
      if (searchTerm.trim().isEmpty) {
        return await _repository.getRolesByBusiness(businessId);
      }
      return await _repository.searchRoles(
        businessId,
        searchTerm,
        limit: limit,
      );
    } catch (e) {
      throw Exception('Failed to search roles: $e');
    }
  }

  Future<List<RoleModel>> getRolesByPermission(String permissionId) async {
    try {
      if (permissionId.isEmpty) {
        throw Exception('Permission ID cannot be empty');
      }
      return await _repository.getRolesByPermission(permissionId);
    } catch (e) {
      throw Exception('Failed to fetch roles by permission: $e');
    }
  }

  // ---------- VALIDATION METHODS ----------

  bool isValidRoleId(String id) {
    return RegExp(r'^[a-z0-9_-]+$').hasMatch(id) && id.isNotEmpty;
  }

  bool isValidRoleName(String name) {
    return name.isNotEmpty && name.length <= 100;
  }

  // ---------- STREAM OPERATIONS ----------

  Stream<RoleModel?> listenToRole(String roleId, String businessId) {
    try {
      if (roleId.isEmpty || businessId.isEmpty) {
        throw Exception('Role ID and Business ID cannot be empty');
      }
      return _repository.listenToRole(roleId);
    } catch (e) {
      throw Exception('Failed to listen to role: $e');
    }
  }

  Stream<List<RoleModel>> listenToBusinessRoles(String businessId) {
    try {
      if (businessId.isEmpty) {
        throw Exception('Business ID cannot be empty');
      }
      return _repository.listenToBusinessRoles(businessId);
    } catch (e) {
      throw Exception('Failed to listen to business roles: $e');
    }
  }
}
