// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBizk3KlngOcSkzP3TrpjfpGWRsioh6b0w',
    appId: '1:880800764076:web:f2500b519cdfb8afe04f09',
    messagingSenderId: '880800764076',
    projectId: 'dineflowx',
    authDomain: 'dineflowx.firebaseapp.com',
    storageBucket: 'dineflowx.firebasestorage.app',
    measurementId: 'G-GLZQT3ZLQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClVfnxrT686m1kwvFi2qC1GC-OvUSyROQ',
    appId: '1:880800764076:android:d26e249c5e00ed58e04f09',
    messagingSenderId: '880800764076',
    projectId: 'dineflowx',
    storageBucket: 'dineflowx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYuVzPwqglYJKTLBhEwXUFxmj7wAOuNHc',
    appId: '1:880800764076:ios:cdd9d6b9e34346fde04f09',
    messagingSenderId: '880800764076',
    projectId: 'dineflowx',
    storageBucket: 'dineflowx.firebasestorage.app',
    iosBundleId: 'com.dineflowx.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYuVzPwqglYJKTLBhEwXUFxmj7wAOuNHc',
    appId: '1:880800764076:ios:cdd9d6b9e34346fde04f09',
    messagingSenderId: '880800764076',
    projectId: 'dineflowx',
    storageBucket: 'dineflowx.firebasestorage.app',
    iosBundleId: 'com.dineflowx.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBizk3KlngOcSkzP3TrpjfpGWRsioh6b0w',
    appId: '1:880800764076:web:1697b93066a42900e04f09',
    messagingSenderId: '880800764076',
    projectId: 'dineflowx',
    authDomain: 'dineflowx.firebaseapp.com',
    storageBucket: 'dineflowx.firebasestorage.app',
    measurementId: 'G-TXN0FDH4PB',
  );

}
